name: Package Windows

on:
  workflow_call:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JBR 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'jetbrains'

      - name: Build Msi
        run: |
          chmod +x gradlew  
          ./gradlew packageMsi

      - name: Upload Msi
        uses: actions/upload-artifact@v4
        with:
          name: app.msi
          path: build\compose\binaries\main\msi\*.msi
          if-no-files-found: error
