name: Build And Deploy

on:
  workflow_dispatch:

jobs:

  build-linux:
    needs: [prepare-project]
    uses: ./.github/workflows/package-linux.yml

  build-windows:
    needs: [prepare-project]
    uses: ./.github/workflows/package-windows.yml

  build-macos:
    needs: [prepare-project]
    uses: ./.github/workflows/package-macos.yml
